# Generated by Django 5.2 on 2025-06-08 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0015_uploadfiles_alter_product_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='photo',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='photos/%Y/%m/%d/', verbose_name='Фото'),
        ),
    ]
