# Generated by Django 5.2 on 2025-06-10 11:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0016_product_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='details',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='market.productdetails', verbose_name='Характеристики'),
        ),
    ]
