# Generated by Django 5.2 on 2025-06-10 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0017_alter_product_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productdetails',
            name='warranty_years',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
