# Generated by Django 5.2 on 2025-06-11 01:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0018_alter_productdetails_warranty_years'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-time_create'], 'permissions': [('social_auth', 'Can login with social account')], 'verbose_name': 'Изделия', 'verbose_name_plural': 'Изделия'},
        ),
    ]
