# Generated by Django 5.2 on 2025-06-11 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0020_comment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-created'], 'permissions': [('can_delete_comment', 'Может удалять комментарии')]},
        ),
    ]
